import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SessionProvider from './SessionProvider'
import { getServerSession } from 'next-auth'
import NavMenu from './components/NavMenu'
import { SocketProvider } from './SocketProvider'
import { authOptions } from './utils/auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)

  return (
      <html lang="en">
        <body className={inter.className}>
          <SessionProvider session={session}>
            <SocketProvider>
              <NavMenu />
              {children}
            </SocketProvider>
          </SessionProvider>
        </body>
      </html>

  )
}
