import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SessionProvider from './SessionProvider'
import { getServerSession } from 'next-auth'
import NavMenu from './components/NavMenu'
import { SocketProvider } from './SocketProvider'
import { authOptions } from './utils/auth'
import Sidebar from './components/Sidebar'
import ReduxProvider from '@/store/ReduxProvider'
import { getChats } from './actions'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)
  const chats = await getChats();

  return (
      <html lang="en">
        <body className={inter.className}>
          <ReduxProvider>
            <SessionProvider session={session}>
              <SocketProvider>
                <NavMenu />
                <main className="flex flex-row mt-[50px] h-[calc(100vh-80px)]">
                    <Sidebar chats={chats} />
                    {children}
                </main>
              </SocketProvider>
            </SessionProvider>
          </ReduxProvider>
        </body>
      </html>

  )
}
